title: 'lovata.ordersshopaholic::lang.property.list_title'
modelClass: Lovata\OrdersShopaholic\Models\Property
list: $/lovata/ordersshopaholic/models/property/columns.yaml
recordUrl: 'lovata/ordersshopaholic/properties/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '25'
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
    column: sort_order
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
