title: 'lovata.ordersshopaholic::lang.title.user_list'
modelClass: Lovata\OrdersShopaholic\Models\User
list: $/lovata/ordersshopaholic/models/user/columns.yaml
recordUrl: 'lovata/ordersshopaholic/users/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '25'
showSetup: true
showCheckboxes: false
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
