name: 'lovata.ordersshopaholic::lang.menu.users'
modelClass: Lovata\OrdersShopaholic\Models\User
form: $/lovata/ordersshopaholic/models/user/fields.yaml
defaultRedirect: lovata/ordersshopaholic/users
create:
    title: 'lovata.ordersshopaholic::lang.title.user_create'
    redirect: 'lovata/ordersshopaholic/users/update/:id'
    redirectClose: lovata/ordersshopaholic/users
    flashSave: 'lovata.ordersshopaholic::lang.message.user_create'
update:
    title: 'lovata.ordersshopaholic::lang.title.user_update'
    redirect: lovata/ordersshopaholic/users
    redirectClose: lovata/ordersshopaholic/users
    flashSave: 'lovata.ordersshopaholic::lang.message.user_update'
    flashDelete: 'lovata.ordersshopaholic::lang.message.user_delete'
preview: {  }
