jobs:
  include:
    - stage: Release
      env:
        - BUILD=true
      script:
        - NAME="ordersshopaholic"
        - zip -r $NAME ./ -x .git/\* -x .gitignore -x .travis.yml -x crowdin.yml -x .editorconfig -x .codeclimate.yml -x PHPMD_custom.xml
        - TAG=$(git describe --tags)
        - FILE="./$NAME.zip"
        - if [[ -e $FILE ]]; then
            NEW_NAME="$NAME-$TAG.$TRAVIS_JOB_ID";
            mv $NAME.zip $NEW_NAME.zip;
          fi
      deploy:
        provider: releases
        api_key:
          secure: ELNn1IOyOgMMGtL8lk/V76ZXJynoBYWw9KjLrWTuR7JmUgVtjW7I70gqAeWf/1UwdTQUdLcQxoJ504k3eixPsWJ26sBd9MNJ2Sgiin4Ba4nqrNCTA6DCYZSrsCJDRG3pRYhuHw44Da3sMZh9RhogkqIC7DRzUuOCIaNrtxGDrdHqf1e+0j1EBNp4XymyJXZB4jJgV0l3sirUGkOVE7l9cSgszicvKFGXA/ID7GAnFM09whdnT4Hfyt36M+gfP2GRTVrj4HCbgdnP4ZL2fKMEEQjUVpOFCQmlE6408kK8x7cPpivs4zmbevlnbK4ngtVMhqHU6KVepyw3gozmDsHqwidchQzsUzpI9fA/H3fQhFetjwYdx0kH9RhM+QSpe58cBqXvGGrfO1B9n0K7JfCBPbac1bY1ZgIJDELjrRFNnuV1AC5iYf4f/wPKwdY8y511Z5XL9bjzBy127zCh2R4HxOCqfXZjGuog9y2iBba/M/ouX2UfuzwQI2WwmCH3z0/pD2r8MpALVQ3s3Z/FPF5J93Fgs2+w+tGxbZaAeDw2P4vY8MgjHdqMl1rHHooukYjROcck5ilSNKxRoERO/s0KnNCyI8eIfsJvZt1U00JOI9oGPcsgCar/GSZqLwXA8D0d3LNV5LjkDrLlif5oZL6dq5pk+RwobJcKRvOcMVtZSd0=
        file: "$NEW_NAME.zip"
        skip_cleanup: true
        on:
          repo: lovata/oc-orders-shopaholic-plugin
