# ===================================
#  Relation Behavior Config
# ===================================

offer:
    label: 'lovata.ordersshopaholic::lang.field.offer_list'
    view:
        list: $/lovata/ordersshopaholic/models/offerorder/columns.yaml
        showSearch: true
        showSorting: true
        showCheckboxes: true
        recordsPerPage: 10
        recordUrl: lovata/shopaholic/products/update/:product_id
        toolbarButtons: remove