# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    status:
        label: 'lovata.ordersshopaholic::lang.field.status'
        modelClass: Lovata\OrdersShopaholic\Models\Status
        nameFrom: name
        conditions: status_id in (:filtered)