# ===================================
#  Relation Behavior Config
# ===================================

order_offer:
    label: 'lovata.ordersshopaholic::lang.order_position.name'
    view:
        list: $/lovata/ordersshopaholic/models/orderposition/order_offer_columns.yaml
        showSearch: true
        showSorting: true
        showCheckboxes: true
        recordsPerPage: 10
        recordUrl: lovata/ordersshopaholic/orderpositions/update/:id
        toolbarButtons: create|delete
    manage:
        form: $/lovata/ordersshopaholic/models/orderposition/order_offer_fields.yaml
order_promo_mechanism:
    label: 'lovata.ordersshopaholic::lang.promo_mechanism.name'
    view:
        list: $/lovata/ordersshopaholic/models/order/order_promo_mechanism_columns.yaml
        showCheckboxes: false
        defaultSort:
            column: priority
            direction: desc
        toolbarButtons: false